function characterTrait(){
    let personnage = [
        "active",
        "adaptive",
        "affability",
        "affectionate",
        "alert"
    ]
    return personnage
}

function characterStyle(){
    let style = [
        "Streetwear",
        "Ethnic",
        "Formal Office Wear",
        "Business Casual",
        "Evening Black Tie",
        "Sports Wear",
        "Girly ",
        "Androgynous",
        "E girl",
        "Scene",
        "Rocker Chic",
        "Skateboarders",
        "Goth",
        "Maternity",
        "Lolita", 
        "Gothic lolita", 
        "Hip Hop", 
        "Chave culture", 
        "Kawaii", 
        "Preppy", 
        "Cowgirl",  
        "Lagenlook",  
        "Girl next door",  
        "Casual Chic",  
        "Geeky chic",
        "Military", 
        "Retro", 
        "Flapper(20’s look)",
        "Tomboy",
        "Garconne look",
        "Vacation(Resort)", 
        "Camp", 
        "Artsy",  
        "Grunge", 
        "Punk",
        "Boho/Bohemian chic",
        "Biker", 
        "Psychedelic",  
        "Cosplay", 
        "Haute Couture",
        "Modest", 
        "Prairie chic", 
        "Rave", 
        "Flamboyant", 
        "Ankara",  
        "Arthoe",  
    ]
    return style 
}

function characterCountry(){
    let country=[    
        "switzerland", 
        "paraguay", 
        "italy",
        "spain",
        "neederland",
        "sweden",
        "cuba", 
        "brazil", 
        "colombia",
        "mexico",
        "canada",
        "united states of america",
        "japan",
        "china",
         
    ]
    return country
}

function characterProfession(){
    let professionArtistic =[
        "Accessory designer",
        "Advertising designer",
        "Animator",
        "Architect",
        "Art administrator", 
        "Artisan",
        "Arts administration",  
        "Art therapist",   
        "Baker",   
        "Ceramics artist",
        "Chief creative officer",
        "Colorist",
        "Concept Artist",
        "Curator",
        "Dancer",
        "Design director",
        "Design strategist",
        "Essayist",
        "Event planner",
        "Fashion designer",
        "Fine artist",
        "Floral designer",
        "Graphic designer",
        "Hairstylist",
        "Illustrator",
        "Tattoo artist",
        "Interior designer",
        "Jewellery designer",
        "Lyricist",
        "Make-up artist",
        "Marine designer",
        "Media designer",
        "Musician",
        "Party planner",
        "Penciller",
        "Photographer",
        "Photojournalist",
        "Potter",
        "Production designer",
        "Sculptor",
        "Set decorator",
        "Set dresser",
        "Singer",
        "Web designer",
        "Wedding planner",
        "Writer",
    ]
    return professionArtistic
}